# Generated by Django 2.2 on 2020-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_category', models.CharField(choices=[('romentic', 'romentic'), ('thriller', 'thriller'), ('horror', 'horror'), ('scientific', 'scientific')], default='', max_length=100)),
                ('movie_name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('year_of_release', models.CharField(max_length=100)),
                ('Director_name', models.CharField(max_length=100)),
                ('Hero_name', models.CharField(max_length=100)),
                ('Heroin_name', models.CharField(max_length=100)),
                ('movie_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
