# Generated by Django 2.2 on 2020-07-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_add_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_movie',
            new_name='movie',
        ),
    ]
