# Generated by Django 2.2 on 2020-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200728_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_seller_email',
            field=models.CharField(default='pratiksuthar1@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
