# Generated by Django 2.2 on 2020-07-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200729_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_seller_email',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_status',
        ),
    ]
