# Generated by Django 2.2 on 2020-07-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200729_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Director_name',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Hero_name',
            new_name='hero',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Heroin_name',
            new_name='heroine',
        ),
    ]
