# Generated by Django 2.2 on 2020-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200729_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='seller_email',
            field=models.CharField(default='pratiksuthar1@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
